name: Flutter Development Workflow

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
        with:
          java-version: 11
          distribution: temurin

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"
          channel: "stable"
      - run: flutter build apk --flavor development --target lib/main_development.dart

      - name: Run Tests
        run: flutter test --coverage --test-randomize-ordering-seed random

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ecommerce_app/build/app/outputs/flutter-apk/app-development-release.apk